export const TYPES = {
    BcryptService:           Symbol.for('BcryptService'),
    EmailManager:            Symbol.for('EmailManager'),
    EmailService:            Symbol.for('EmailService'),
    UsersRepository:         Symbol.for('UsersRepository'),
    UsersQueryRepository:    Symbol.for('UsersQueryRepository'),
    UsersService:            Symbol.for('UsersService'),
    BlogsRepository:         Symbol.for('BlogsRepository'),
    BlogsQueryRepository:    Symbol.for('BlogsQueryRepository'),
    BlogsService:            Symbol.for('BlogsService'),
    PostsRepository:         Symbol.for('PostsRepository'),
    PostsQueryRepository:    Symbol.for('PostsQueryRepository'),
    PostsService:            Symbol.for('PostsService'),
    CommentsRepository:      Symbol.for('CommentsRepository'),
    CommentsQueryRepository: Symbol.for('CommentsQueryRepository'),
    CommentsService:         Symbol.for('CommentsService'),
    SecurityRepository:      Symbol.for('SecurityRepository'),
    SecurityQueryRepository: Symbol.for('SecurityQueryRepository'),
    SecurityService:         Symbol.for('SecurityService'),
    AuthRepository:          Symbol.for('AuthRepository'),
    AuthQueryRepository:     Symbol.for('AuthQueryRepository'),
    JwtService:              Symbol.for('JwtService'),
    AuthService:             Symbol.for('AuthService'),
    TestingRepository:       Symbol.for('TestingRepository'),
}
